/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Frontend;

import Backend.Penumpang;
import Backend.Pesawat;
import Backend.Transaksi;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class FrmTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form FrmTransaksi
     */
        String type1 = null;
        int harga_pesawat;
    public FrmTransaksi() {
        initComponents();
        tampilkanData();
        kosongkanForm();
    }
    public void kosongkanForm(){
        txtidTransaksi.setText("0");
        txtcariPenumpang.setText("0");
        CombocariPesawat.setAction(null);
        txtjumlahTiket.setText("");
        txttotalBayar.setText("");
    }
    
    public final void tampilkanData(){
        String[] kolom = {"ID Transaksi","ID Penumpang","ID Pesawat", "Jumlah Tiket", "Total bayar"};
        ArrayList<Transaksi> list = new Transaksi().getAll();
        Object rowData[] = new Object[5];
        
        tblTransaksi.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for (Transaksi trn : list) {
            rowData[0] = trn.getIdTransaksi ();
            rowData[1] = trn.getPenumpang().getIdPenumpang ();
            rowData[2] = trn.getPesawat().getIdPesawat ();
            rowData[3] = trn.getJumlahTiket();
            rowData[4] = trn.getTotalBayar();
        
            ((DefaultTableModel)tblTransaksi.getModel()).addRow(rowData);
        }
    }
    
    public final void cari(String keyword){
        String[] kolom = {"ID Transaksi","ID Penumpang","ID Pesawat", "Jumlah Tiket", "Total bayar"};
        ArrayList<Transaksi> list = new Transaksi().search(keyword);
        Object rowData[] = new Object[5];
        
        tblTransaksi.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for (Transaksi trn : list) {
            rowData[0] = trn.getIdTransaksi ();
            rowData[1] = trn.getPenumpang().getIdPenumpang ();
            rowData[2] = trn.getPesawat().getIdPesawat ();
            rowData[3] = trn.getJumlahTiket();
            rowData[4] = trn.getTotalBayar();
        
            ((DefaultTableModel)tblTransaksi.getModel()).addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtidTransaksi = new javax.swing.JTextField();
        txtcariPenumpang = new javax.swing.JTextField();
        txtjumlahTiket = new javax.swing.JTextField();
        txttotalBayar = new javax.swing.JTextField();
        btncariPenumpang = new javax.swing.JButton();
        btncariPesawat = new javax.swing.JButton();
        lblpenumpang = new javax.swing.JLabel();
        lblpesawat = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btntambahBaru = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        CombocariPesawat = new javax.swing.JComboBox();
        btnhitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Transaksi");

        jLabel2.setText("ID Penumpang");

        jLabel3.setText("ID Pesawat");

        jLabel4.setText("Jumlah Tiket");

        jLabel5.setText("Total Bayar");

        txtidTransaksi.setEnabled(false);

        txtjumlahTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahTiketActionPerformed(evt);
            }
        });

        txttotalBayar.setEnabled(false);
        txttotalBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalBayarActionPerformed(evt);
            }
        });

        btncariPenumpang.setText("Cari");
        btncariPenumpang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariPenumpangActionPerformed(evt);
            }
        });

        btncariPesawat.setText("Cari");
        btncariPesawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariPesawatActionPerformed(evt);
            }
        });

        lblpenumpang.setText("namaPenumpang");

        lblpesawat.setText("namaPesawat");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btntambahBaru.setText("Tambah Baru");
        btntambahBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahBaruActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btncari.setText("Cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTransaksi);

        CombocariPesawat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih ID Pesawat", "1", "2", "3" }));
        CombocariPesawat.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                CombocariPesawatInputMethodTextChanged(evt);
            }
        });
        CombocariPesawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombocariPesawatActionPerformed(evt);
            }
        });

        btnhitung.setText("Hitung");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcariPenumpang)
                            .addComponent(txtjumlahTiket)
                            .addComponent(txttotalBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(CombocariPesawat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtidTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btncariPenumpang)
                                .addGap(18, 18, 18)
                                .addComponent(lblpenumpang))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btncariPesawat)
                                .addGap(18, 18, 18)
                                .addComponent(lblpesawat))
                            .addComponent(btnhitung)))
                    .addComponent(btnSimpan)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btntambahBaru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnhapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btncari))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcariPenumpang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncariPenumpang)
                    .addComponent(lblpenumpang))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btncariPesawat)
                    .addComponent(lblpesawat)
                    .addComponent(CombocariPesawat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtjumlahTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhitung))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txttotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambahBaru)
                    .addComponent(btnhapus)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransaksiMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblTransaksi.getModel();
        int row = tblTransaksi.getSelectedRow();
        
        txtidTransaksi.setText(model.getValueAt(row, 0).toString());
        txtcariPenumpang.setText(model.getValueAt(row, 1).toString());
        CombocariPesawat.setToolTipText(model.getValueAt(row, 2).toString());
        txtjumlahTiket.setText(model.getValueAt(row, 3).toString());
        txttotalBayar.setText(model.getValueAt(row, 4).toString()); 
    }//GEN-LAST:event_tblTransaksiMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {           
            Transaksi trn = new Transaksi();

            trn.setIdTransaksi(Integer.parseInt(txtidTransaksi.getText()));
            Penumpang penumpang = new Penumpang().getById(Integer.parseInt(txtcariPenumpang.getText()));
            trn.setPenumpang(penumpang);
            Pesawat pesawat = new Pesawat().getById(Integer.parseInt(CombocariPesawat.getToolTipText()));
            trn.setPesawat(pesawat);
            trn.setJumlahTiket(Integer.parseInt(txtjumlahTiket.getText()));
            trn.setTotalBayar(Double.parseDouble(txttotalBayar.getText()));
            trn.save();
            txtidTransaksi.setText(Integer.toString(trn.getIdTransaksi()));
            tampilkanData();
        } catch (Exception e) {
            System.out.println("Exception :" + e);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btncariPenumpangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariPenumpangActionPerformed
        // TODO add your handling code here:
        Penumpang penumpang = new Penumpang();
        penumpang = penumpang.getById(Integer.parseInt(txtcariPenumpang.getText()));
        if (String.valueOf(penumpang.getNamaPenumpang()).equalsIgnoreCase("null")) {
            lblpenumpang.setText("Data tidak ditemukan");
        } else {
            lblpenumpang.setText(String.valueOf(penumpang.getNamaPenumpang()));
        }
    }//GEN-LAST:event_btncariPenumpangActionPerformed

    private void btncariPesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariPesawatActionPerformed
        // TODO add your handling code here:
        Pesawat pesawat = new Pesawat();
        pesawat = pesawat.getById(Integer.parseInt(CombocariPesawat.getToolTipText()));
        if (String.valueOf(pesawat.getNamaPesawat()).equalsIgnoreCase("null")) {
            lblpesawat.setText("Data tidak ditemukan");
        } else {
            lblpesawat.setText(String.valueOf(pesawat.getNamaPesawat()));
        }
    }//GEN-LAST:event_btncariPesawatActionPerformed

    private void btntambahBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahBaruActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_btntambahBaruActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)tblTransaksi.getModel();
        int row = tblTransaksi.getSelectedRow();
        
        Transaksi trs = new Transaksi().getById(Integer.parseInt(model.getValueAt(row,0).toString()));
        trs.delete();
        kosongkanForm();
        tampilkanData();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:Pesawat pesawat = new Pesawat();
        cari(txtcari.getText());
    }//GEN-LAST:event_btncariActionPerformed

    private void txtjumlahTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahTiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlahTiketActionPerformed

    private void txttotalBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalBayarActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_txttotalBayarActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        // TODO add your handling code here:
        int total = 0;
        if(CombocariPesawat.getSelectedIndex()==0){
            type1 = "1";
            harga_pesawat = 2000000;
        }
        else if(CombocariPesawat.getSelectedIndex()==1){
            type1 = "2";
            harga_pesawat = 1000000;
        }
        else if(CombocariPesawat.getSelectedIndex()==2){
            type1 = "3";
            harga_pesawat = 1500000;
        }
        CombocariPesawat.setToolTipText(type1);
        total = harga_pesawat * Integer.parseInt(txtjumlahTiket.getText());
        txttotalBayar.setText(Double.toString(total));
        
//        total = Integer.parseInt(CombocariPesawat.getToolTipText())* Integer.parseInt(txtjumlahTiket.getText());
    }//GEN-LAST:event_btnhitungActionPerformed

    private void CombocariPesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombocariPesawatActionPerformed
        // TODO add your handling code here:

        if(CombocariPesawat.getSelectedIndex()==0){
            type1 = "1";
            harga_pesawat = 2000000;
        }
        else if(CombocariPesawat.getSelectedIndex()==1){
            type1 = "2";
            harga_pesawat = 1000000;
        }
        else if(CombocariPesawat.getSelectedIndex()==2){
            type1 = "3";
            harga_pesawat = 1500000;
        }
        CombocariPesawat.setToolTipText(type1);
        txttotalBayar.setText(Double.toString(harga_pesawat));
    }//GEN-LAST:event_CombocariPesawatActionPerformed

    private void CombocariPesawatInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_CombocariPesawatInputMethodTextChanged
        // TODO add your handling code here:
        CombocariPesawat.addItem("PILIH ID Pesawat");
        CombocariPesawat.addItem("1");
        CombocariPesawat.addItem("2");
        CombocariPesawat.addItem("3");
    }//GEN-LAST:event_CombocariPesawatInputMethodTextChanged

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CombocariPesawat;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btncariPenumpang;
    private javax.swing.JButton btncariPesawat;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnhitung;
    private javax.swing.JButton btntambahBaru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblpenumpang;
    private javax.swing.JLabel lblpesawat;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtcariPenumpang;
    private javax.swing.JTextField txtidTransaksi;
    private javax.swing.JTextField txtjumlahTiket;
    private javax.swing.JTextField txttotalBayar;
    // End of variables declaration//GEN-END:variables
}
